name: Go Web Server CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x  # Replace '1.x' with the desired Go version

      - name: Install dependencies
        run: go mod download

      - name: Build Go Binary
        run: go build -o ./go-crud-api

      - name: Build Docker Image
        run: docker build -t ./go-crud-api .

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          script: |
            # Remove existing container (if applicable)
            docker stop go-crud-api || true
            docker rm go-crud-api || true

            # Pull the latest image from the registry (if applicable)
            docker pull my-registry/go-crud-api || true

            # Run the Docker container
            docker run -d -p 3000:3000 go-crud-api
