name: Go Web Server CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x  # Replace '1.x' with the desired Go version

      - name: Install dependencies
        run: go mod download

      - name: Build Go Binary
        run: go build -o ./go-crud-api 

      - name: Build Docker Image
        run: docker build -t go-crud-api .